/**
 * setup-fonts.mjs  — Self-host Montserrat to eliminate font-caused CLS
 *
 * What it does:
 *  1. Fetches the Google Fonts CSS (with a modern UA so we get woff2 URLs)
 *  2. Downloads every referenced .woff2 file into  fonts/
 *  3. Writes  fonts/montserrat.css  with local @font-face rules +
 *     font-display: optional  (no swap = zero CLS)
 *  4. Patches every HTML file to replace the Google Fonts <link> tags with
 *     a single local <link rel="stylesheet" href="fonts/montserrat.css"> and
 *     <link rel="preload"> tags for the two heaviest-used weights (400 & 700)
 *
 * Run:  node setup-fonts.mjs
 */

import { mkdir, writeFile, readFile } from 'fs/promises';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { createWriteStream } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { pipeline } from 'stream/promises';
import { Readable } from 'stream';

const ROOT    = path.dirname(fileURLToPath(import.meta.url));
const FONTS   = path.join(ROOT, 'fonts');
const CSS_OUT = path.join(FONTS, 'montserrat.css');

// Unified weight set covering every page in the site
const GOOGLE_URL =
  'https://fonts.googleapis.com/css2?' +
  'family=Montserrat:ital,wght@' +
  '0,400;0,500;0,600;0,700;0,800;0,900;1,700' +
  '&display=swap';

// Pretend to be Chrome 124 on Windows so Google Fonts returns woff2
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ' +
           'AppleWebKit/537.36 (KHTML, like Gecko) ' +
           'Chrome/124.0.0.0 Safari/537.36';

const HTML_FILES = [
  'index.html', 'admissions.html', 'fees.html', 'calendar.html',
  'gallery.html', 'news.html', 'careers.html', 'resources.html',
];

// ─── helpers ──────────────────────────────────────────────────────────────────

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.text();
}

async function downloadFile(url, dest) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const ws = createWriteStream(dest);
  await pipeline(Readable.fromWeb(res.body), ws);
}

// ─── Step 1: fetch Google Fonts CSS ──────────────────────────────────────────

console.log('\n🔤  Bright Sparks — Font Self-Hosting Setup\n');
console.log('① Fetching Google Fonts CSS …');
await mkdir(FONTS, { recursive: true });

const gfontsCSS = await fetchText(GOOGLE_URL);

// ─── Step 2: extract @font-face blocks ───────────────────────────────────────

// Each block looks like:
// /* latin */
// @font-face {
//   font-family: 'Montserrat';
//   font-style: normal;
//   font-weight: 700;
//   font-display: swap;
//   src: url(https://fonts.gstatic.com/…/….woff2) format('woff2');
//   unicode-range: U+0000-00FF, …;
// }

const facePattern =
  /\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;

const faces = [];
let m;
while ((m = facePattern.exec(gfontsCSS)) !== null) {
  const subset = m[1].trim();
  const block  = m[2];

  const style   = (block.match(/font-style:\s*(\w+)/)  || [])[1] || 'normal';
  const weight  = (block.match(/font-weight:\s*([\d]+)/) || [])[1] || '400';
  const srcUrl  = (block.match(/url\(([^)]+\.woff2)\)/) || [])[1] || '';
  const unicode = (block.match(/unicode-range:\s*([^;]+)/) || [])[1] || '';

  if (srcUrl) faces.push({ subset, style, weight, srcUrl, unicode });
}

console.log(`   Found ${faces.length} @font-face blocks`);

// ─── Step 3: download woff2 files ────────────────────────────────────────────

console.log('② Downloading woff2 files …');

// Track: style→weight→subset → local filename
const localMap = new Map(); // srcUrl → local filename

for (const face of faces) {
  const filename = `Montserrat-${face.weight}-${face.style}-${face.subset.replace(/\s+/g, '_')}.woff2`;
  const dest = path.join(FONTS, filename);
  localMap.set(face.srcUrl, filename);

  if (!existsSync(dest)) {
    await downloadFile(face.srcUrl, dest);
    console.log(`   ✓  ${filename}`);
  } else {
    console.log(`   ↩  ${filename}  (already exists)`);
  }
}

// ─── Step 4: write local fonts/montserrat.css ────────────────────────────────

console.log('③ Writing fonts/montserrat.css …');

let localCSS = '/* Montserrat — self-hosted, generated by setup-fonts.mjs */\n\n';

for (const face of faces) {
  const file = localMap.get(face.srcUrl);
  localCSS +=
    `@font-face {\n` +
    `  font-family: 'Montserrat';\n` +
    `  font-style: ${face.style};\n` +
    `  font-weight: ${face.weight};\n` +
    `  font-display: optional;\n` +   // ← key: no swap = zero CLS
    `  src: url('${file}') format('woff2');\n` +
    (face.unicode ? `  unicode-range: ${face.unicode};\n` : '') +
    `}\n\n`;
}

await writeFile(CSS_OUT, localCSS, 'utf8');
console.log(`   ✓  fonts/montserrat.css  (${faces.length} faces)`);

// ─── Step 5: find the latin-400 and latin-700 woff2 filenames for preloading ─

function localFileFor(weight, style, subset) {
  const face = faces.find(
    f => f.weight === String(weight) && f.style === style && f.subset === subset
  );
  return face ? localMap.get(face.srcUrl) : null;
}

const preload400 = localFileFor(400, 'normal', 'latin');
const preload700 = localFileFor(700, 'normal', 'latin');

if (!preload400 || !preload700) {
  console.warn('   ⚠  Could not find latin-400 or latin-700 — check faces list');
}

// ─── Step 6: patch HTML files ─────────────────────────────────────────────────

console.log('④ Patching HTML files …');

// Regex that matches the entire Google Fonts block:
//   optional <link rel="preconnect" …> lines
//   the <link rel="preload" as="style" …> line
//   the <noscript> line
// We allow for slight variations between pages
const GFONTS_BLOCK = /(<link[^>]+googleapis\.com[^>]*>\s*\n?)+(<link[^>]+gstatic\.com[^>]*>\s*\n?)*(<link[^>]+googleapis\.com\/css2[^>]+>\s*\n?)(<noscript>[^<]*<link[^>]+googleapis\.com\/css2[^>]+>[^<]*<\/noscript>\s*\n?)?/g;

// Build the replacement block
const PRELOAD_LINES = [
  preload400
    ? `<link rel="preload" as="font" type="font/woff2" crossorigin href="fonts/${preload400}">`
    : '',
  preload700
    ? `<link rel="preload" as="font" type="font/woff2" crossorigin href="fonts/${preload700}">`
    : '',
].filter(Boolean).join('\n') + '\n';

const NEW_BLOCK =
  `<link rel="stylesheet" href="fonts/montserrat.css">\n` +
  PRELOAD_LINES;

let patchedCount = 0;

for (const file of HTML_FILES) {
  const fullPath = path.join(ROOT, file);
  if (!existsSync(fullPath)) continue;

  let html = readFileSync(fullPath, 'utf8');
  const before = html;

  // Replace the google fonts block
  html = html.replace(GFONTS_BLOCK, NEW_BLOCK);

  if (html !== before) {
    writeFileSync(fullPath, html, 'utf8');
    console.log(`   ✓  ${file}`);
    patchedCount++;
  } else {
    console.log(`   –  ${file}  (no Google Fonts block found)`);
  }
}

// ─── Done ─────────────────────────────────────────────────────────────────────

console.log(`
${'─'.repeat(60)}
✅  Done!

  fonts/          — ${faces.length} woff2 files + montserrat.css
  HTML patched    — ${patchedCount} files updated

Upload the  fonts/  folder to your server alongside index.html.
The fonts are now served from your own domain:
  • No Google Fonts DNS lookup
  • No TLS handshake to fonts.gstatic.com
  • font-display: optional  → zero CLS (no mid-render swap)
  • <link rel="preload">    → latin-400 and latin-700 start loading
    before the CSS parser even reads montserrat.css
${'─'.repeat(60)}
`);
